### ISSUE TITLE
-Wsign-compare warnings

### ISSUE THREAD

**Issue by marioortizmanero** [adamstark/AudioFile#21] opened 2019-12-01 22:53 UTC
When using this library, I get a few warnings related to `-Wsign-compare`. Are there any plans on fixing it? It shouldn't be too hard.

```
In file included from src/main.cpp:3:
src/../include/AudioFile.h: In instantiation of ‘bool AudioFile<T>::decodeWaveFile(std::vector<unsigned char>&) [with T = double]’:
src/../include/AudioFile.h:403:16:   required from ‘bool AudioFile<T>::load(std::string) [with T = double; std::string = std::__cxx11::basic_string<char>]’
src/main.cpp:20:40:   required from here
src/../include/AudioFile.h:468:28: warning: comparison of integer expressions of different signedness: ‘int32_t’ {aka ‘int’} and ‘uint32_t’ {aka ‘unsigned int’
} [-Wsign-compare]
  468 |     if ((numBytesPerSecond != (numChannels * sampleRate * bitDepth) / 8) || (numBytesPerBlock != (numChannels * numBytesPerSample)))
      |         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/../include/AudioFile.h: In instantiation of ‘bool AudioFile<T>::decodeAiffFile(std::vector<unsigned char>&) [with T = double]’:
src/../include/AudioFile.h:407:16:   required from ‘bool AudioFile<T>::load(std::string) [with T = double; std::string = std::__cxx11::basic_string<char>]’
src/main.cpp:20:40:   required from here
src/../include/AudioFile.h:599:90: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<unsigned char>::size_type’ {aka
long unsigned int’} [-Wsign-compare]
  599 |     if ((soundDataChunkSize - 8) != totalNumAudioSampleBytes || totalNumAudioSampleBytes > (fileData.size() - samplesStartIndex))
      |                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/../include/AudioFile.h: In instantiation of ‘int AudioFile<T>::getIndexOfString(std::vector<unsigned char>&, std::string) [with T = double; std::string = s
td::__cxx11::basic_string<char>]’:
src/../include/AudioFile.h:428:28:   required from ‘bool AudioFile<T>::decodeWaveFile(std::vector<unsigned char>&) [with T = double]’
src/../include/AudioFile.h:403:16:   required from ‘bool AudioFile<T>::load(std::string) [with T = double; std::string = std::__cxx11::basic_string<char>]’
src/main.cpp:20:40:   required from here
src/../include/AudioFile.h:1007:23: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<unsigned char>::size_type’ {aka
‘long unsigned int’} [-Wsign-compare]
 1007 |     for (int i = 0; i < source.size() - stringLength;i++)
      |                     ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/../include/AudioFile.h: In instantiation of ‘void AudioFile<T>::clearAudioBuffer() [with T = double]’:
src/../include/AudioFile.h:490:5:   required from ‘bool AudioFile<T>::decodeWaveFile(std::vector<unsigned char>&) [with T = double]’
src/../include/AudioFile.h:403:16:   required from ‘bool AudioFile<T>::load(std::string) [with T = double; std::string = std::__cxx11::basic_string<char>]’
src/main.cpp:20:40:   required from here
src/../include/AudioFile.h:950:23: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::vector<double, std::allocato
r<double> >, std::allocator<std::vector<double, std::allocator<double> > > >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  950 |     for (int i = 0; i < samples.size();i++)
```

Great job on the library by the way!! Super useful and lightweight :)

**Comment by marioortizmanero** [comment] 2019-12-02 00:30
Also, naive question after reading the library:

When calling load() with a WAV file, you use push_back() to append the new values to the vector. Would something like samples[i][j], where is i is the channel and j is the channel data, speed up the process? You already know the length from the headers anyway.

**Comment by adamstark** [comment] 2020-02-28 22:07
Thank you! Could you please let me know which compiler generated these warnings?

Adam :)

**Comment by adamstark** [comment] 2020-02-29 00:12
This should be all fixed in the new version - let me know if not!

Adam

**Comment by clone45** [comment] 2020-05-27 01:40
Hello!  I'm getting the same types of warnings.  I'm building modules for VCV Rack.  

```
# make install
g++  -std=c++11 -Wsuggest-override   -fPIC -I/c/code/Rack-SDK/include -I/c/code/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unus-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/GrainEngineMK2.cpp.o src/GrainEngineMK2.cpp
In file included from src/Common/sample.hpp:3,
                 from src/GrainEngineMK2.cpp:11:
src/Common/AudioFile.h: In instantiation of 'bool AudioFile<T>::decodeWaveFile(std::vector<unsigned char>&) [with T = double]':
src/Common/AudioFile.h:417:16:   required from 'bool AudioFile<T>::load(std::string) [with T = double; std::string = std::__cxx11::basic_string<char>]'
src/Common/sample.hpp:36:24:   required from here
src/Common/AudioFile.h:482:28: warning: comparison of integer expressions of different signedness: 'int32_t' {aka 'int'} and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
  482 |     if ((numBytesPerSecond != (numChannels * sampleRate * bitDepth) / 8) || (numBytesPerBlock != (numChannels * numBytesPerSample)))
```

**Comment by adamstark** [comment] 2020-06-17 21:09
Hi there, can you confirm that this is still happening on the latest version on develop?

**Comment by clone45** [comment] 2020-06-18 02:47
Yes, confirmed.  I was able to fix it by doing the following:

```
    uint16_t audioFormat = twoBytesToInt (fileData, f + 8);
    uint16_t numChannels = twoBytesToInt (fileData, f + 10);
    sampleRate = (uint32_t) fourBytesToInt (fileData, f + 12);
    uint32_t numBytesPerSecond = fourBytesToInt (fileData, f + 16);
    uint16_t numBytesPerBlock = twoBytesToInt (fileData, f + 20);
    bitDepth = (unsigned int) twoBytesToInt (fileData, f + 22);
```

But I don't know if that's going to have any unintended side effects.  I also get the following warning:

```
src/Common/AudioFile.h: In instantiation of 'bool AudioFile<T>::decodeWaveFile(std::vector<unsigned char>&) [with T = float]':
src/Common/AudioFile.h:435:16:   required from 'bool AudioFile<T>::load(std::string) [with T = float; std::string = std::__cxx11::basic_string<char>]'
src/Common/sample.hpp:75:29:   required from here
src/Common/AudioFile.h:559:59: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  559 |                     sample = (T)reinterpret_cast<float&> (sampleAsInt);
```

Thanks!  I very much appreciate it!

**Comment by adamstark** [comment] 2020-07-03 19:57
I've just pushed to the develop branch something that _hopefully_ will fix this - would you be able to check and confirm?

Thanks!

**Comment by adamstark** [comment] 2020-10-17 13:26
I'm assuming this is fixed now and closing this issue - let me know if it is still a problem :)

**Closed as completed by adamstark** 2020-10-17 13:26 UTC
